export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOAD = "LOAD";

export const REGISTER_MSG = "REGISTER_MSG";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT = "LOGOUT";

export const GET_USERS = "ALL_USERS_DATA";
export const ERR_USERS = "ERR_USERS";

export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";

export const POST_EMAIL_SUCCESS = "POST_EMAIL_SUCCESS";
export const POST_EMAIL_ERR = "POST_EMAIL_ERR";
export const EMAIL_MSG_SUCCESS = "EMAIL_MSG_SUCCESS";
export const EMAIL_MSG_ERR = "EMAIL_MSG_ERR";

export const ADD_IMG_SUCCESS = "ADD_IMG_SUCCESS";
export const ADD_IMG_ERR = "ADD_IMG_ERR";
export const TOUR_CREATE_SUCCESS = "TOUR_CREATED";
export const TOUR_CREATE_ERR = "TOUR_CREATE_ERR";

export const GET_TOURS = "GET_TOURS";
export const ERR_TOURS = "ERR_TOURS";

export const DELETE_TOUR = "DELETE_TOUR";
export const UPDATE_ACTIVE_STATUS = "UPDATE_ACTIVE_STATUS";
export const UPDATE_CURRENT_STATUS = "UPDATE_CURRENT_STATUS";
export const UPDATE_FINISHED_STATUS = "UPDATE_FINISHED_STATUS";

export const GET_TOUR = "GET_TOUR";

export const TOUR_JOIN_SUCCESS = "TOUR_JOIN_SUCCESS";

export const SUPERDEST_CREATE_SUCCESS = "SUPERDEST_CREATE_SUCCESS";
export const SUPERDEST_CREATE_ERR = "SUPERDEST_CREATE_ERR";

export const GET_CUSTOM_TOURS = "GET_CUSTOM_TOURS";
export const ERR_CUSTOM_TOURS = "ERR_CUSTOM_TOURS";

export const DELETE_CUSTOM_TOUR = "DELETE_CUSTOM_TOUR";

export const GET_CUSTOM_TOUR = "GET_CUSTOM_TOUR";

export const DESTINATION_CREATE_SUCCESS = "DESTINATION_CREATE_SUCCESS";

export const REMOVE_DESTINATION = "REMOVE_DESTINATION";

export const GET_DESTINATION = "GET_DESTINATION";

export const UPDATE_DESTINATION_ACTIVE = "UPDATE_DESTINATION_ACTIVE";

export const CUSTOMTOUR_JOIN_SUCCESS = "CUSTOMTOUR_JOIN_SUCCESS";
export const CUSTOMTOUR_CREATE_ERR = "CUSTOMTOUR_CREATE_ERR";

export const TOUR_JOINING = "TOUR_JOINING";
export const ERR_JOINING = "ERR_JOINING";
